### PR TITLE
Random State 333 and 222

### PR DESCRIPTION
**Pull request by gyroninja**
I added back random state scrambles for 3x3 and 2x2. I updated the test.js file also. I removed checking length for 3x3 scrambles because that no longer applies. The 5x5 scrambles were also using a weird chain syntax where it was setting the length first. Setting the length first only worked for NxN puzzles and not other ones. With this update it breaks it if you did length first so I reordered it in the test.

### CODE REVIEW

**Comment by nickcolley** [comment]
So does this remove the possibility of having certain length scrambles?

**Comment by nickcolley** [comment]
I'm cool with this going in as we can raise issues and solve them later, one thing I'm unsure about is why the 555 tests fail now and required a reordering?

**Comment by gyroninja** [comment]
What happened is that you were changing the length of the current scrambler then changing the scrambler. This would cause it not to take effect. Only with NNN cubes could you specify the length before the puzzle type.

You can still set the length of the scramble as long as you set it after setting the type.

**Comment by nickcolley** [comment]
There's a bunch of code here related to the drawing of a cube, do you want to remove them before we merge or get this in and refactor later?

**Comment by gyroninja** [comment]
I think you should merge it and the cut out the rendering stuff.

**Comment by NickColley** [comment]
Yeah there's important code here that I don't want to be blocked on removing the unnecessary code for now. Will raise issues to follow up, you can tackle them if you fancy it otherwise I'll get to it :+1:

**Comment by NickColley** [comment]
Also thank you very much for the contribution, I appreciate it! :+1: :tada:

**Pull request merged**
