### PR TITLE
fixed clock scrambles

### PR DESCRIPTION
**Pull request by coder13**
When setting the type to 'clock', scrambo would return an array of objects with scramble_string type. This pull requests fixes that.

### CODE REVIEW

**Comment by nickcolley** [comment]
Looks good to me, will review properly then publish a new version thanks a lot @coder13 :+1:

**Comment by coder13** [comment]
Didn't mean to add the skewb scrambler to this pull request.

**Comment by nickcolley** [comment]
Skewb sounds great too yeah, feel free to open a new PR if you want. Thanks

**Comment by nickcolley** [comment]
@coder13 Sorry for the wait, this is great, thanks so much for contributing! :+1:

**Pull request merged**
